version: "3.9"

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        USER_ID: '${WWWUSER:-1000}'
        GROUP_ID: '${WWWGROUP:-1000}'
        USER: '${USER:-whoami}'
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www

  nginx:
    image: nginx:1.23-alpine
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d:ro

